// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUIzhNqVotUWbKAfwhyoRdNHFM4kh2mOo',
    appId: '1:345739362198:web:bd5b84e678f7b853ea27b7',
    messagingSenderId: '345739362198',
    projectId: 'shopappp-7e713',
    authDomain: 'shopappp-7e713.firebaseapp.com',
    databaseURL: 'https://shopappp-7e713-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopappp-7e713.firebasestorage.app',
    measurementId: 'G-PSCFR83FZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOw7XZdTvpkyFuzj7I_4p48l7sZP1RbfM',
    appId: '1:345739362198:android:257a65403622d191ea27b7',
    messagingSenderId: '345739362198',
    projectId: 'shopappp-7e713',
    databaseURL: 'https://shopappp-7e713-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopappp-7e713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH1RZR1tEk320fsGO7-dLSKyzhzYsndtU',
    appId: '1:345739362198:ios:f2d6a7693dc84029ea27b7',
    messagingSenderId: '345739362198',
    projectId: 'shopappp-7e713',
    databaseURL: 'https://shopappp-7e713-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopappp-7e713.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH1RZR1tEk320fsGO7-dLSKyzhzYsndtU',
    appId: '1:345739362198:ios:f2d6a7693dc84029ea27b7',
    messagingSenderId: '345739362198',
    projectId: 'shopappp-7e713',
    databaseURL: 'https://shopappp-7e713-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopappp-7e713.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUIzhNqVotUWbKAfwhyoRdNHFM4kh2mOo',
    appId: '1:345739362198:web:ba515ee515d31de8ea27b7',
    messagingSenderId: '345739362198',
    projectId: 'shopappp-7e713',
    authDomain: 'shopappp-7e713.firebaseapp.com',
    databaseURL: 'https://shopappp-7e713-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopappp-7e713.firebasestorage.app',
    measurementId: 'G-8HYN4GS37E',
  );
}
